# Main configuration file
# All values can be overridden using environment variables
# Example: ML_MODEL_DIR=custom/path python your_script.py

model:
  dir: "models"
  version: "v1"
  format: "saved_model"
  min_accuracy: 0.90
  max_inference_time: 100  # ms

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  validation_split: 0.2

production:
  monitoring: true
  version_control: true
  metrics_tracking: true
  monitoring_interval: 60  # seconds
  alert_threshold: 0.85

data:
  dir: "data"
  cache_dir: ".cache"
